services:
  postgresdb:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: student-enrolment-management-system-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  student-enrolment-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bartmilo/student-enrolment-management-system:latest
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/student-enrolment-management-system-db

volumes:
  postgres_data:
